In [ ]:
! pip install tensorflow 

In [ ]:
!pip install split-folders

In [3]:
import os
import numpy as np
import pandas as pd
import glob
import cv2 as cv
import caer
import canaro


In [4]:
import splitfolders

In [5]:
os.chdir('F:\Data Science Study material\Futura labs MT')

In [6]:
os.getcwd()

'F:\\Data Science Study material\\Futura labs MT'

In [7]:
input_folder='F:\Data Science Study material\Futura labs MT\COVID-19_Radiography_Dataset'

In [8]:
splitfolders.ratio(input_folder,output='F:\Data Science Study material\Futura labs MT\COVID_19',seed=42,ratio=(0.7,0.2,0.1),group_prefix=None)

Copying files: 15153 files [05:02, 50.16 files/s]


In [9]:
import keras
from keras.layers import *
from keras.models import *
from keras.preprocessing import image

In [34]:
#CNN based model in keras 
model=Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(299,299,3)))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))


model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='sigmoid'))

model.compile(loss=keras.losses.binary_crossentropy,optimizer='adam',metrics=['accuracy'])

    


In [35]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 297, 297, 32)      896       
                                                                 
 conv2d_5 (Conv2D)           (None, 295, 295, 64)      18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 147, 147, 64)     0         
 2D)                                                             
                                                                 
 dropout_4 (Dropout)         (None, 147, 147, 64)      0         
                                                                 
 conv2d_6 (Conv2D)           (None, 145, 145, 64)      36928     
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 72, 72, 64)       0         
 2D)                                                  

In [36]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold

In [13]:
train_datagen=image.ImageDataGenerator(
rescale=1./255,
shear_range=0.2,
zoom_range=0.2,
horizontal_flip=True)

test_dataset= image.ImageDataGenerator(rescale=1/255)

In [14]:
train_generator=train_datagen.flow_from_directory(
'F:/Data Science Study material/Futura labs MT/COVID_19/train',
target_size=(224,224),
batch_size=32,
class_mode='categorical')

Found 10606 images belonging to 3 classes.


In [15]:
train_generator.class_indices

{'COVID': 0, 'Normal': 1, 'Viral Pneumonia': 2}

In [16]:
validation_generator=test_dataset.flow_from_directory(
'F:/Data Science Study material/Futura labs MT/COVID_19/val',
target_size=(224,224),
batch_size=32,
class_mode='categorical')

Found 4547 images belonging to 3 classes.


In [17]:
hist= model.fit_generator(
      train_generator,
      steps_per_epoch=8,
      epochs=10,
      validation_data=validation_generator,
      validation_steps=2)

<ipython-input-17-36fd4f111deb>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  hist= model.fit_generator(


Epoch 1/10
8/8 [==============================] - 255s 31s/step - loss: 0.7584 - accuracy: 0.5625 - val_loss: 0.5126 - val_accuracy: 0.7344
Epoch 2/10
8/8 [==============================] - 242s 30s/step - loss: 0.5816 - accuracy: 0.6562 - val_loss: 0.5901 - val_accuracy: 0.7812
Epoch 3/10
8/8 [==============================] - 223s 30s/step - loss: 0.5101 - accuracy: 0.6891 - val_loss: 0.5195 - val_accuracy: 0.6875
Epoch 4/10
8/8 [==============================] - 242s 30s/step - loss: 0.5743 - accuracy: 0.6328 - val_loss: 0.5851 - val_accuracy: 0.6562
Epoch 5/10
8/8 [==============================] - 251s 32s/step - loss: 0.5276 - accuracy: 0.6328 - val_loss: 0.5737 - val_accuracy: 0.6406
Epoch 6/10
8/8 [==============================] - 246s 31s/step - loss: 0.5197 - accuracy: 0.6680 - val_loss: 0.5165 - val_accuracy: 0.6250
Epoch 7/10
8/8 [==============================] - 241s 30s/step - loss: 0.5383 - accuracy: 0.6445 - val_loss: 0.5163 - val_accuracy: 0.7031
Epoch 8/10
8/8 [====

In [ ]:
#testing

In [19]:
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import img_to_array



In [38]:
path = "F:/Data Science Study material/Futura labs MT/COVID_19/val/COVID/COVID-19.png"
img = load_img(path,target_size= (299,299))

img = img_to_array(img)/255
img = np.array([img])
#img.shape

In [39]:
img

array([[[[0.01568628, 0.01568628, 0.01568628],
         [0.02745098, 0.02745098, 0.02745098],
         [0.02352941, 0.02352941, 0.02352941],
         ...,
         [0.01960784, 0.01960784, 0.01960784],
         [0.01960784, 0.01960784, 0.01960784],
         [0.01568628, 0.01568628, 0.01568628]],

        [[0.01960784, 0.01960784, 0.01960784],
         [0.02745098, 0.02745098, 0.02745098],
         [0.02745098, 0.02745098, 0.02745098],
         ...,
         [0.02352941, 0.02352941, 0.02352941],
         [0.02352941, 0.02352941, 0.02352941],
         [0.01960784, 0.01960784, 0.01960784]],

        [[0.01568628, 0.01568628, 0.01568628],
         [0.02352941, 0.02352941, 0.02352941],
         [0.02745098, 0.02745098, 0.02745098],
         ...,
         [0.02352941, 0.02352941, 0.02352941],
         [0.02352941, 0.02352941, 0.02352941],
         [0.01960784, 0.01960784, 0.01960784]],

        ...,

        [[0.02745098, 0.02745098, 0.02745098],
         [0.03921569, 0.03921569, 0.03921569]

In [40]:
predict_x=model.predict(img) 
predict_x

1/1 [==============================] - 1s 789ms/step


array([[0.5232397 , 0.50667393, 0.5027051 ]], dtype=float32)

In [41]:
#predict_x=model.predict(img) 
classes_x=np.argmax(predict_x,axis=1)
classes_x


array([0], dtype=int64)